repository_type: pipeline
lint:
  nextflow_config:
    - config_defaults:
        - params.logo_file
        - params.css_file
        - params.citations_file
        - params.report_file
nf_core_version: "2.14.1"
